"""DJI SRT Telemetry Parser.

Parses DJI drone SRT subtitle files containing GPS coordinates, altitude,
gimbal angles, and camera telemetry data.
"""

import logging
import re

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class DJISRTParser:
    """Parser for DJI SRT telemetry files.

    Extracts GPS coordinates, altitude, gimbal angles, and focal length
    from subtitle files generated by DJI drones.

    Attributes:
        packets: List of parsed telemetry packets as dictionaries.
    """

    # Regex patterns for extracting telemetry data
    TIMESTAMP_PATTERN = re.compile(r"(\d{2}:\d{2}:\d{2},\d{3}) --> (\d{2}:\d{2}:\d{2},\d{3})")
    LATITUDE_PATTERN = re.compile(r"\[latitude:\s*([+-]?\d+\.?\d*)\]")
    LONGITUDE_PATTERN = re.compile(r"\[longitude:\s*([+-]?\d+\.?\d*)\]")
    REL_ALT_PATTERN = re.compile(r"\[rel_alt:\s*([+-]?\d+\.?\d*)\s+")
    ABS_ALT_PATTERN = re.compile(r"abs_alt:\s*([+-]?\d+\.?\d*)\]")
    GB_YAW_PATTERN = re.compile(r"\[gb_yaw:\s*([+-]?\d+\.?\d*)\s+")
    GB_PITCH_PATTERN = re.compile(r"gb_pitch:\s*([+-]?\d+\.?\d*)\s+")
    GB_ROLL_PATTERN = re.compile(r"gb_roll:\s*([+-]?\d+\.?\d*)\]")
    FOCAL_LEN_PATTERN = re.compile(r"\[focal_len:\s*(\d+\.?\d*)\]")

    def __init__(self, srt_content: str):
        """Initialize parser with SRT content.

        Args:
            srt_content: Raw SRT file content as string.
        """
        self.srt_content = srt_content
        self.packets: list[dict] = []
        self._parse()

    def _parse_timestamp(self, timestamp: str) -> float:
        """Convert SRT timestamp (HH:MM:SS,mmm) to seconds (float).

        Args:
            timestamp: Timestamp string in format HH:MM:SS,mmm

        Returns:
            Timestamp as seconds (float)
        """
        # Replace comma with dot for milliseconds
        timestamp = timestamp.replace(",", ".")
        parts = timestamp.split(":")
        hours = int(parts[0])
        minutes = int(parts[1])
        seconds = float(parts[2])
        return hours * 3600 + minutes * 60 + seconds

    def _parse(self) -> None:
        """Parse SRT content and populate packets list."""
        # Split into blocks (separated by blank lines)
        blocks = re.split(r"\n\s*\n", self.srt_content.strip())

        for block in blocks:
            if not block.strip():
                continue

            try:
                packet = self._parse_block(block)
                if packet:
                    self.packets.append(packet)
            except Exception as e:
                logger.warning(f"Failed to parse block: {e}")
                continue

    def _parse_block(self, block: str) -> dict | None:
        """Parse a single SRT block into a packet dictionary.

        Args:
            block: Single SRT entry block

        Returns:
            Dictionary with parsed telemetry data, or None if invalid
        """
        lines = block.strip().split("\n")
        if len(lines) < 2:
            return None

        # Parse frame index
        try:
            index = int(lines[0].strip())
        except ValueError:
            index = 0

        # Parse timestamp line
        timestamp_match = self.TIMESTAMP_PATTERN.search(lines[1])
        if not timestamp_match:
            return None

        start_time = self._parse_timestamp(timestamp_match.group(1))
        end_time = self._parse_timestamp(timestamp_match.group(2))

        # Combine all content lines for telemetry extraction
        content = " ".join(lines[2:])

        # Extract telemetry values
        packet = {
            "index": index,
            "start_time": start_time,
            "end_time": end_time,
            "latitude": self._extract_float(content, self.LATITUDE_PATTERN),
            "longitude": self._extract_float(content, self.LONGITUDE_PATTERN),
            "rel_alt": self._extract_float(content, self.REL_ALT_PATTERN),
            "abs_alt": self._extract_float(content, self.ABS_ALT_PATTERN),
            "gb_yaw": self._extract_float(content, self.GB_YAW_PATTERN),
            "gb_pitch": self._extract_float(content, self.GB_PITCH_PATTERN),
            "gb_roll": self._extract_float(content, self.GB_ROLL_PATTERN),
            "focal_len": self._extract_float(content, self.FOCAL_LEN_PATTERN),
        }

        return packet

    def _extract_float(self, content: str, pattern: re.Pattern) -> float | None:
        """Extract float value using regex pattern.

        Args:
            content: String to search
            pattern: Compiled regex pattern

        Returns:
            Extracted float value, or None if not found
        """
        match = pattern.search(content)
        if match:
            try:
                return float(match.group(1))
            except (ValueError, IndexError):
                pass
        return None

    def interpolate_packet(self, timestamp_seconds: float) -> dict | None:
        """Interpolate telemetry packet at given timestamp.

        Performs linear interpolation between surrounding packets for smooth
        tracking at any timestamp.

        Args:
            timestamp_seconds: Target timestamp in seconds

        Returns:
            Interpolated packet dictionary, or None if no packets available
        """
        if not self.packets:
            return None

        # If timestamp is before first packet, return first packet
        if timestamp_seconds <= self.packets[0]["start_time"]:
            return self.packets[0].copy()

        # If timestamp is after last packet, return last packet
        if timestamp_seconds >= self.packets[-1]["start_time"]:
            return self.packets[-1].copy()

        # Find surrounding packets
        prev_packet = None
        next_packet = None

        for packet in self.packets:
            if packet["start_time"] <= timestamp_seconds:
                prev_packet = packet
            else:
                next_packet = packet
                break

        if prev_packet is None:
            return self.packets[0].copy()

        if next_packet is None:
            return prev_packet.copy()

        # Linear interpolation
        time_range = next_packet["start_time"] - prev_packet["start_time"]
        if time_range == 0:
            return prev_packet.copy()

        ratio = (timestamp_seconds - prev_packet["start_time"]) / time_range

        interpolated = prev_packet.copy()
        interpolated["start_time"] = timestamp_seconds
        interpolated["end_time"] = timestamp_seconds

        # Interpolate numeric fields
        numeric_fields = [
            "latitude",
            "longitude",
            "rel_alt",
            "abs_alt",
            "gb_yaw",
            "gb_pitch",
            "gb_roll",
            "focal_len",
        ]

        for field in numeric_fields:
            if prev_packet[field] is not None and next_packet[field] is not None:
                interpolated[field] = (
                    prev_packet[field] + (next_packet[field] - prev_packet[field]) * ratio
                )

        return interpolated

    def get_packet_at_index(self, index: int) -> dict | None:
        """Get packet at specific frame index.

        Args:
            index: Frame index (1-based)

        Returns:
            Packet dictionary, or None if not found
        """
        for packet in self.packets:
            if packet["index"] == index:
                return packet
        return None

    def __len__(self) -> int:
        """Return number of parsed packets."""
        return len(self.packets)

    def __repr__(self) -> str:
        return f"DJISRTParser(packets={len(self.packets)})"


def load_srt_file(filepath: str) -> DJISRTParser:
    """Load and parse an SRT file.

    Args:
        filepath: Path to SRT file

    Returns:
        DJISRTParser instance with parsed data
    """
    with open(filepath, encoding="utf-8") as f:
        content = f.read()
    return DJISRTParser(content)


if __name__ == "__main__":
    # Basic test
    import sys

    if len(sys.argv) > 1:
        filepath = sys.argv[1]
        parser = load_srt_file(filepath)
        logger.info(f"Loaded {len(parser.packets)} packets")

        if parser.packets:
            logger.info(f"First packet: {parser.packets[0]}")
            logger.info(f"Last packet: {parser.packets[-1]}")

            # Test interpolation at 1.5 seconds
            interp = parser.interpolate_packet(1.5)
            logger.info(f"Interpolated at 1.5s: {interp}")
